kind: pipeline
type: docker

steps:
- name: build
  image: docker:dind
  privileged: true
  commands:
   - docker build . -t www

- name: deploy
  image: docker:dind
  privileged: true
  commands:
   - docker kill $(docker ps --filter "ancestor=www" | awk '{ print $1 }' | tail +2)
   - docker run -d www
