kind: pipeline
type: docker
name: build

steps:
- name: build
  image: docker-compose
  privileged: true
  commands:
   - docker-compose build

- name: deploy
  image: docker-compose
  privileged: true
  commands:
   - docker-compose stop
   - docker-compose up -d

volumes:
- name: dockersock
  path: /var/run
